DROP table PRODUCT;
DROP table PRODUCT_OFFER;
CREATE TABLE IF NOT EXISTS PRODUCT (
  id          INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_name VARCHAR(64) NOT NULL,
  price   INTEGER);

CREATE TABLE IF NOT EXISTS PRODUCT_OFFER (
  id          INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  price   INTEGER,
  units   INTEGER,
  product_id INTEGER,
  CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES PRODUCT (id) ON DELETE CASCADE ON UPDATE CASCADE);